root: true
env:
  browser: true
  es2020: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "prettier"
settings:
  react:
    version: "18"
plugins:
  - "@typescript-eslint"
  - "react"
  - "react-hooks"
  - "react-refresh"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: "module"
rules:
  react/jsx-uses-react: "off"
  react/react-in-jsx-scope: "off"